apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
data:
  {{- $path := printf "%s" .Values.configPath }}
  {{- (.Files.Glob $path).AsConfig | nindent 2 }}

