{{- with .Values.canaryDeployment -}}
{{- if and .enable (.config | default dict).path (.config | default dict).version -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-canary-config-%s" $.Values.appName .config.version }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- toYaml $.Values.labels | nindent 4 }}
data:
  {{- $path := printf "%s" .config.path }}
  {{- ($.Files.Glob $path).AsConfig | nindent 2 }}
{{- end -}}
{{- end -}}