{{- with .Values.gateway -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $.Values.appName }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts: {{ .hosts | toYaml | nindent 8 }}
      port:
        name: http
        number: 80
        protocol: http
{{- end -}}