{{- $appName := .Values.appName -}}
{{- $namespace := .Values.namespace -}}
{{- $host := printf "%s.%s.svc.cluster.local" $appName $namespace -}}
{{- $isCanaryEnabled :=  and (.Values.canaryDeployment).enable ((.Values.canaryDeployment).token).key ((.Values.canaryDeployment).token).value -}}

{{- if $isCanaryEnabled -}}
{{- with .Values.canaryDeployment -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
spec:
  hosts:
    - {{ $host }}
    {{- if ($.Values.gateway).hosts }}
    {{- $.Values.gateway.hosts | toYaml | nindent 4 }}
    {{- end }}
  {{- if ($.Values.gateway).hosts }}
  gateways:
    - {{ $appName }}
  {{- end }}
  http:
    - match:
        - headers:
            {{ .token.key }}:
              exact: {{ .token.value }}
      route:
        - destination:
            host: {{ $host }}
            subset: canary
            {{- if ($.Values.gateway).targetPort }}
            port:
              number: {{ $.Values.gateway.targetPort }}
            {{- end }}
      {{- include "kx.httpRetry" $ | indent 6 }}
    - route:
        - destination:
            host: {{ $host }}
            subset: stable
            {{- if ($.Values.gateway).targetPort }}
            port:
              number: {{ $.Values.gateway.targetPort }}
            {{- end }}
      {{- include "kx.httpRetry" $ | indent 6 }}
{{- end -}}
{{- end -}}

{{- if not $isCanaryEnabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
spec:
  hosts:
    - {{ $host }}
    {{- if (.Values.gateway).hosts }}
    {{- .Values.gateway.hosts | toYaml | nindent 4 }}
    {{- end }}
  {{- if (.Values.gateway).hosts }}
  gateways:
    - {{ $appName }}
  {{- end }}
  http:
    - route:
        - destination:
            host: {{ $host }}
            subset: stable
            {{- if ($.Values.gateway).targetPort }}
            port:
              number: {{ $.Values.gateway.targetPort }}
            {{- end }}
      {{- include "kx.httpRetry" . | indent 6 }}
{{- end -}}