{{- $appName := .Values.appName -}}
{{- $namespace := .Values.namespace -}}
{{- $host := printf "%s.%s.svc.cluster.local" $appName $namespace -}}
{{- $isCanaryEnabled :=  and (.Values.canaryDeployment).enable ((.Values.canaryDeployment).token).key ((.Values.canaryDeployment).token).value -}}


{{- with .Values.canaryDeployment -}}
{{- $isVirtualServiceSkipped := (has "virtualservice" .skip) -}}
{{- if and $isCanaryEnabled (not $isVirtualServiceSkipped) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
spec:
  hosts:
    - {{ $host }}
    {{- if ($.Values.gateway).hosts }}
    {{- $.Values.gateway.hosts | toYaml | nindent 4 }}
    {{- end }}
  {{- if ($.Values.gateway).hosts }}
  gateways:
    - {{ $appName }}
  {{- end }}
  http:
    - match:
        - headers:
            {{ .token.key }}:
              exact: {{ .token.value }}
      route:
        - destination:
            host: {{ $host }}
            subset: canary
    - route:
        - destination:
            host: {{ $host }}
            subset: stable
{{- end -}}
{{- end -}}

{{- if and .Values.gateway (not $isCanaryEnabled) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ $appName }}
  namespace: {{ $namespace }}
spec:
  hosts:
    - {{ $host }}
    {{- .Values.gateway.hosts | toYaml | nindent 4 }}
  gateways:
    - {{ $appName }}
  http:
    - route:
        - destination:
            host: {{ $host }}
{{- end -}}