appName: REPLACE_WITH_APP_NAME

namespace: REPLACE_WITH_NAMESPACE

labels:
  env: prod

annotations:
  contact: REPLACE_WITH_OWNER

replicaCount: REPLACE_WITH_REPLICA_COUNT

image:
  repo: REPLACE_WITH_APP_NAME
  tag: REPLACE_WITH_APP_VERSION
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "150Mi"
    cpu: "100m"
  limits:
    memory: "800Mi"
    cpu: "1000m"

config:
  path: REPLACE_WITH_CONFIG_PATH
  version: REPLACE_WITH_CONFIG_VERSION
  mounts:
    - name: REPLACE_WITH_APP_NAME-config
      mountPath: REPLACE_WITH_CONFIG_MOUNT_PATH
      subPath: config.js
      readOnly: true
      items:
        - key: config.js
          path: config.js

startupProbe:
  httpGet:
    port: REPLACE_WITH_SERVICE_PORT
    path: REPLACE_WITH_PROBE_HTTP_GET_PATH
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 6

livenessProbe:
  httpGet:
    port: REPLACE_WITH_SERVICE_PORT
    path: REPLACE_WITH_PROBE_HTTP_GET_PATH
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    port: REPLACE_WITH_SERVICE_PORT
    path: REPLACE_WITH_PROBE_HTTP_GET_PATH
  initialDelaySeconds: 3
  periodSeconds: 3
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 2
