appName: REPLACE_WITH_APP_NAME

namespace: REPLACE_WITH_NAMESPACE

labels:
  env: prod

annotations:
  contact: REPLACE_WITH_OWNER

replicaCount: REPLACE_WITH_REPLICA_COUNT

image:
  namespace: REPLACE_WITH_NAMESPACE
  repo: REPLACE_WITH_APP_NAME
  tag: REPLACE_WITH_APP_VERSION
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: "150Mi"
    cpu: "100m"
  limits:
    memory: "800Mi"
    cpu: "1000m"

config:
  path: REPLACE_WITH_CONFIG_PATH
  version: v1.0.0
  mounts:
    - name: REPLACE_WITH_APP_NAME-config
      mountPath: /usr/src/app/config.js
      subPath: config.js
      readOnly: true
      items:
        - key: config.js
          path: config.js

startupProbe:
  httpGet:
    host: localhost
    port: REPLACE_WITH_SERVICE_PORT
    path: REPLACE_WITH_PROBE_HTTP_GET_PATH
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 6

livenessProbe:
  httpGet:
    host: localhost
    port: REPLACE_WITH_SERVICE_PORT
    path: REPLACE_WITH_PROBE_HTTP_GET_PATH
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 3
